# Generated by Django 5.2.11 on 2026-02-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_news_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пусто или 0 — бесплатный курс. Иначе — платный, с сертификатом.', max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
